---
title: "02_clean"
format: html
---

### Load the Dataset

```{r}
library(tidyverse)

kidney_raw <- read_csv("../data/01_data_load.csv")

```

### Changing the column names

```{r}
kidney_clean <- kidney_raw %>%
  rename(
    id = id,
    age = age,
    blood_pressure = bp,
    specific_gravity = sg,
    albumin = al,
    sugar = su,
    red_blood_cells = rbc,
    pus_cells = pc,
    pus_cell_clumps = pcc,
    bacteria = ba,
    blood_glucose_random = bgr,
    blood_urea = bu,
    serum_creatinine = sc,
    sodium = sod,
    potassium = pot,
    hemoglobin = hemo,
    packed_cell_volume = pcv,
    white_blood_cell_count = wc,
    red_blood_cell_count = rc,
    hypertension = htn,
    diabetes_mellitus = dm,
    coronary_artery_disease = cad,
    appetite = appet,
    pedal_edema = pe,
    anemia = ane,
    classification = classification
  )

```

### Column types fixed

In the raw data, some columns with numeric observations were classified as characters; these are changed into the numeric type.

```{r}
# if colums are numbrs - change to numeric, if characters - change to factor
kidney_clean <- kidney_clean %>%
  mutate(
    packed_cell_volume = as.numeric(packed_cell_volume),
    white_blood_cell_count = as.numeric(white_blood_cell_count),
    red_blood_cell_count = as.numeric(red_blood_cell_count),
    across(where(is.character), as.factor)
  )


```
<<<<<<< HEAD
=======

### NA's

The missing values are going to be handled in separate analysis individually. The percentage of NAs in each column is summarized here:

```{r}
nas<-kidney_clean %>% 
     summarise(across(everything(), ~mean(is.na(.)) * 100))

view(nas)
```

### Save clean data in a new file

```{r}
# write a clean data
write_csv(kidney_clean, "../data/02_dat_clean.csv")
```
>>>>>>> aab313cda5fee105c4f2b35e6927ab04b920925c
